version: 2.1

jobs:
  audit_build_lint_test:
    docker:
      - image: cimg/node:24.13.1
    steps:
      - checkout
      - run:
          name: Install PNPM 10.23.0
          command: |
            sudo npm install --global corepack@latest
            corepack enable
            corepack use pnpm@10.23.0
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Security audit
          command: pnpm audit --audit-level=moderate
      - run:
          name: Check format
          command: pnpm check-format
      - run:
          name: Build packages
          command: pnpm build
      - run:
          name: Check exports
          command: pnpm check-exports
      - run:
          name: Check lint
          command: pnpm lint
      - run:
          name: Test packages
          command: pnpm test

workflows:
  audit_build_lint_test:
    jobs:
      - audit_build_lint_test
